language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  -  yarn global add gatsby-cli

script:
  - yarn lint
  - yarn build

deploy:
  - provider: script
    script: yarn website:deploy
    skip_cleanup: true
    on:
      all_branches: true
  - provider: npm
    edge: true
    email: "${NPM_EMAIL}"
    api_key: "${NPM_API_TOKEN}"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
